// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWmuF6rksg_kH9u8S3-p_AUG7xFZ97enM',
    appId: '1:687641064898:web:190bd43518684c6269d25b',
    messagingSenderId: '687641064898',
    projectId: 'e-commerce-e529b',
    authDomain: 'e-commerce-e529b.firebaseapp.com',
    storageBucket: 'e-commerce-e529b.appspot.com',
    measurementId: 'G-S9F6L3Y224',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJq64Jctm3voWDk_tR0VDWIbOfN_8C6g8',
    appId: '1:687641064898:android:32aae9d16ca3fff569d25b',
    messagingSenderId: '687641064898',
    projectId: 'e-commerce-e529b',
    storageBucket: 'e-commerce-e529b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvpL8a0GWlgJWxAnQmEEigKU_P-eUrrY',
    appId: '1:687641064898:ios:93aa8c658a96d88569d25b',
    messagingSenderId: '687641064898',
    projectId: 'e-commerce-e529b',
    storageBucket: 'e-commerce-e529b.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPvpL8a0GWlgJWxAnQmEEigKU_P-eUrrY',
    appId: '1:687641064898:ios:93aa8c658a96d88569d25b',
    messagingSenderId: '687641064898',
    projectId: 'e-commerce-e529b',
    storageBucket: 'e-commerce-e529b.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWmuF6rksg_kH9u8S3-p_AUG7xFZ97enM',
    appId: '1:687641064898:web:190bd43518684c6269d25b',
    messagingSenderId: '687641064898',
    projectId: 'e-commerce-e529b',
    authDomain: 'e-commerce-e529b.firebaseapp.com',
    storageBucket: 'e-commerce-e529b.appspot.com',
    measurementId: 'G-S9F6L3Y224',
  );

}